tinkerbell/actions

- actions/image2disk/v1/README.md
The `http://` needs adding to the URL otherwise it wont be parsed correctly.
Fixes documentation to ensure action is used correctly.
Fixes: #
I have:
> Fixes to URL

- .mergify.yml
The default configuration we have for mergify rely on base branch to
be master. But hub uses main.
> chore(mergify): enable support for main branch

- actions/syslinux/v1/Dockerfile
- actions/syslinux/v1/Makefile
- actions/syslinux/v1/README.md
- actions/syslinux/v1/go.mod
- actions/syslinux/v1/go.sum
- actions/syslinux/v1/main.go
This adds a syslinux action, specifically for version `3.86`, others can be added later.
VMware in their infinite wisdom are pinned to a twelve year old bootloader... this allows us to deploy vSphere.
Fixes: #
I have:
```
docker run --privileged \
-e DEST_DISK=/dev/sdb \
-e SYSLINUX_VERSION=3.86 \
-e DEST_PARTITION=/dev/sdb1 \
thebsdbox/syslinux:1.0.0 
```
> This adds Syslinux installation support as an action

- actions/image2disk/v1/main.go
```
time="2021-03-04T13:18:50Z" level=info msg="Successfully written [%s] to [%s]http://192.168.1.2/focal-server-cloudimg-amd64.raw/dev/sdb"
```
Wrong function is being called here `info` -> `infof`
The success meeting is mis-formatted.
Fixes: #
I have:
> Fixes formatting issue

- actions/image2disk/v1/go.mod
- actions/image2disk/v1/pkg/image/image.go
Currently when using image2disk, if it creates new partitions on the underlying device those partitions are not accessible to following actions. 
This allows following actions to use any partitions created by this action.
Tested manually using the steps here: https://github.com/detiber/sandbox/tree/captee
Prior to the change the workflow would fail on a newly provisioned worker, after the workflow was successful on a newly provisioned worker.
This will allow users to more easily chain actions without having to insert an explicit partprobe or reboot 
I have:
> [WIP] Do the equivalent of partprobe after writing in image2disk

- actions/cexec/v1/Dockerfile
- actions/cexec/v1/Makefile
- actions/cexec/v1/README.md
- actions/cexec/v1/go.mod
- actions/cexec/v1/go.sum
- actions/cexec/v1/main.go
This adds `cexec` Chroot Exec
Allows for one-shot operations to run commands inside a newly written Operating system
Fixes: #
runs `ls` twice as the comand
```
CEXEC - Chroot Exec
------------------------
INFO[0000] Mounted [/dev/sdb1] -> [/mountAction]
INFO[0000] Changing root before executing command
bin   dev  home  lib32	libx32	    media  mountAction	proc  run   snap  sys  usr
boot  etc  lib	 lib64	lost+found  mnt    opt		root  sbin  srv   tmp  var
bin   dev  home  lib32	libx32	    media  mountAction	proc  run   snap  sys  usr
boot  etc  lib	 lib64	lost+found  mnt    opt		root  sbin  srv   tmp  var
```
I have:
> cexec action

- actions/archive2disk/v1/main.go
Confusion between BLOCK_DEVICE and DEST_DISK.. Moved to DEST_DISK as we hit a partition not the raw block device.
It was confusing before. 
Fixes: #29
I have:
> Aligns readme to environment vars

- actions/rootio/v1/pkg/types.go/metadata.go
Fix err check for metadata json unmarshal
It is needed to see error if hw data is invalid.
Fixes: #
Local setup.
Users currently cannot see if there is an error related to metadata extraction.
I have:
> Fix err check for metadata json unmarshal

- actions/image2disk/v1/pkg/image/image.go
Cleaning up the image2disk package: 
- Removing unneeded code 
- Fixing fmt.Errorf() formating
- Don't swallow errors when they occur
Some errors are being lost due to bad formatting in addition to breaking go lints.
Fixes: #39
Reran the workflow and the errors are showing up again.
I have:
> cleanup image2disk package:

- .github/workflows/ci.yaml
- hack/ci-check.sh
As part of the continuous integration workflows I would like to know
which actions will get build as soon as the pull request will be merged.
> Check actions who needs to be re-build

- cmd/hub/cmd/build.go
Right now we have `--dry-run` to identify the actions we need to build
inside a particular git range.
We want to actually try to build the image but the `push` option was
fixed to `true`. This commit adds a `--push` option that has to be
specified in order to push the image to a registry.
This follows the same behavior buildx has.
Signed-off-by: Gianluca Arbezzano <ciao@gianarb.it>
> Take image push option from the outside

- .github/workflows/ci.yaml
- actions/slurp/v1/main.go
- hack/ci-check.sh
The hub CLI build command can get git history only from PR coming from this repo. It does not work with a fork. This is because we fetch only the destination repository, not the one where the PR is coming from.
PR coming from fork should work
> Add action build as validation step in CI

- .github/workflows/cd-action-build.yaml
- actions/archive2disk/v1/main.go
- hack/action-build-and-deploy.sh
- shell.nix
Bootstrap a bash script that runs `hub build` to compile and push docker
images for the actions that changed on Quay.io
The workflow only runs on push against the main branch.
Signed-off-by: Gianluca Arbezzano <ciao@gianarb.it>
> Add GitHub Action workflow to build and deploy actions

- .envrc
- .github/workflows/cd-action-build.yaml
- .github/workflows/ci.yaml
- cmd/hub/cmd/generate.go
Main work is to fix the `Build and push new actions to Quay.io` action to not attempt to login to Quay from PRs from forks. PRs from forks don't have access to secrets and thus the docker login step fails.
I've also cleaned up the workflow files a bit so that each step has a name and an empty space around it so the files are easier to grok.
I've also added a .envrc so we can make use of direnv + nix-shell.
Should fix CI that is holding back #60.
> Fix CI for PRs from forks

- actions/kexec/v1/Dockerfile
- actions/kexec/v1/Makefile
- actions/kexec/v1/cmd/kexec.go
Add debug log lines for `kexec` action. Debugging
When Kexec doesn't work, it'd be nice to know where in the process it breaks down.
> "Works on my machine"
> -Every pull request author
But really, I ran this in an effort to diagnose #57 
```
INFO[0000] Loaded boot config: &grub.Config{Name:"'Debian GNU/Linux' ", Kernel:"/boot/vmlinuz-4.19.0-16-cloud-amd64", Initramfs:"/boot/initrd.img-4.19.0-16-cloud-amd64", KernelArgs:"root=UUID=af5f8c82-a495-40e0-b3e6-f361abeec5a4 ro nosplash text biosdevname=0 net.ifnames=0 console=tty0 console=ttyS0,115200 earlyprintk=ttyS0,115200 consoleblank=0 systemd.show_status=true", Multiboot:"", MultibootArgs:"", Modules:[]string(nil)} 
INFO[0000] Running Kexec: kernel: /mountAction/boot/vmlinuz-4.19.0-16-cloud-amd64, initrd: …
```
> Add kexec debug log lines

- actions/image2disk/v1/pkg/image/image.go
In cases where you're writing a file system image to an existing
partition, it's not really needed, but it's simpler and safer to just
ignore the error rather than try to figure out if it's a disk or
partition.
Signed-off-by: Steve Wills <steve@mouf.net>
Trying to write a file system image to an existing partition (`md`), I get an error on the re-probe. Seems safer and simpler to just ignore it.
In cases where you want to write a file system image rather than a disk image.
Fixes: N/A
In VMs
Should be no impact
I have:
- [N/A] updated the documentation and/or roadmap (if required)
- [N/A] added unit or e2e tests
- [N/A] provided instructions on how to upgrade
> Ignore errors for the part probe

- actions/rootio/v1/cmd/rootio.go
- actions/rootio/v1/pkg/types.go/metadata.go
- actions/rootio/v1/test/mbr.json
- actions/rootio/v1/test/standard.json
As it is now, rootio doesn't unmarshal the metadata returned for the node and doesn't perform any specified actions.
Fixes: https://github.com/tinkerbell/hub/issues/75
This has been tested by building a rootio with this change and running in the workflow.
I have:
- updated and tested with the test json files
> Align rootio with the current metadata format

- actions/image2disk/v1/pkg/image/image.go
Signed-off-by: Steve Wills <steve@mouf.net>
Change the flags to os.OpenFile so the path is not created.
image2disk will create a file in /dev if the device doesn't exist. This is not what is desired.
Fixes: #
Tested in my environment
Users can think image2disk succeeded in writing the image to disk when in reality it only created a file in /dev/ containing what the disk should contain.
I have:
- [N/A] updated the documentation and/or roadmap (if required)
- [N/A] added unit or e2e tests
- [N/A] provided instructions on how to upgrade
> Don't create, the device should exist

- actions/cexec/v1/main.go
Mount sysfs inside the chroot
Fixes: #82
Locally. Before the change:
```
INFO[0000] Changing root before executing command
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Unknown device "/dev/sda2": No such device
Unknown device "/dev/sda1": No such device
Unknown device "/dev/sda1": No such device
Unknown device "/dev/sda2": No such device
....
Found linux image: /boot/vmlinuz-5.4.0-99-generic
Found initrd image: /boot/initrd.img-5.4.0-99-generic
...
Unknown device "/dev/sda2": No such device
Unknown device "/dev/sda3": No such device
Unknown device "/dev/sda2": No such device
Unknown device "/dev/sda2": No such device
Cannot find list of partitions!  (Try mounting /sys.)
done
```
With the change:
```
INFO[0000] …
```
> cexec: mount sysfs inside the chroot.

- go.mod
- go.sum
- shell.nix
As discussed in the community meeting: this updates the go.mod to use 1.17 keeping up-to-date with the times.
> Update to go1.17

- actions/rootio/v1/cmd/rootio.go
- actions/rootio/v1/pkg/storage/partition.go
- actions/rootio/v1/pkg/storage/wipe.go
Extracting the Wipe functionality and add it as a dedicated command, where user can only wipe disks without any partitioning, using the metadata of the Hardware. 
This is very helpful, when the provisioned machine, is gonna be used by some storage specific services or SDS operator, as some of those operators don't use disks that are in a specific status(for example if the disks have partitions, the storage operator would considered this disk is being used by anther software and wouldn't use and utilize it).
Fixes: https://github.com/tinkerbell/hub/issues/90
It was tested by using this commit and build an image out of it, where this image has been use as a workflow to de provision a machine. 
NA
I have:
> Extract disk wiping from disk partitioning

- actions/rootio/v1/README.md
This PR fixes broken link for custom partitioning & raid in docs.
Broken Link
Fixes: #
I have:
> fix: Docs link for custom partitioning & raid

- actions/image2disk/v1/pkg/image/image.go
Added .bz2 extension support as both .bz2 and .bzip2 are commonly used file extensions for the same bzip2 compression format.
> image2disk: support .bz2 extension

- actions/rootio/v1/Dockerfile
- actions/rootio/v1/cmd/rootio.go
- actions/rootio/v1/pkg/lvm/lvm.go
- actions/rootio/v1/pkg/storage/lvm.go
- actions/rootio/v1/pkg/storage/partition.go
- actions/rootio/v1/pkg/types.go/metadata.go
Adding the ability to create LVM in the partition command by adding the volume_groups object to the metadata
#36 
Fixes: #
I tested the changes on Dell PowerEdge R650 and Lenovo ThinkSystem SR630 V2 servers with the standard hook kernel.
I ran the action rootio with the partition command and added lvm-related data to the metadata. After creating the logical volumes, I initialized the file systems on them using the rootio format command.
Changes do not affect the current code if you do not add lvm-related parameters to the metadata.
To start using the changes, just add an optional array describing volume groups to the metadata
I have:
> add the ability to create lvm in the partition command

- .github/mergify.yml
Update mergify to require successful builds for both PRs and queueing.
> Update mergify to require successful build

- cexec/README.md
- cexec/main.go
- go.mod
- go.sum
Cleaning up the code base for improved maintainability. Add option to use the host's /etc/resolv.conf in the chroot env. This resolves issues with DNS based network calls for things like package managers, etc.
Fixes: #92 
I have:
> [CEXEC] Code clean up; Add resolv.conf fixing in chroot:

- .github/workflows/release.yml
- Makefile
This gets both arch images push to quay.io
Fixes: #
I have:
> Update release to handle arm64 and amd64:

- .github/workflows/ci.yml
- .github/workflows/release.yml
- grub2disk/Dockerfile
This is attempting to improve the time it takes to build both architectures and splits each image into its own GitHub actions job so that failures can be retried independently. 
Fixes: #
I have:
> Refactor multi arch builds

- archive2disk/Dockerfile
- cexec/Dockerfile
- image2disk/Dockerfile
- kexec/Dockerfile
- oci2disk/Dockerfile
- qemuimg2disk/Dockerfile
- rootio/Dockerfile
- slurp/Dockerfile
- syslinux/Dockerfile
- writefile/Dockerfile
Docker build is warning about:
"`FromAsCasing: 'as' and 'FROM' keywords' casing do not match`" This resolves the warning.
Fixes: #
I have:
> Fix Docker build warning:

- kexec/README.md
- kexec/cmd/kexec.go
Add the ability to specify custom location for `grub.cfg`.
Ubuntu 24.04 cloud image mounts the `/boot` partition. The default `/boot/grub/grub.cfg` location is invalid when we mount the partition. The location when there is a `/boot` partition is `grub/grub.cfg`.
Fixes: #142 
- Tested on code vagrant with libvirt from https://github.com/tinkerbell/playground/blob/main/stack/docs/quickstarts/VAGRANTLVIRT.md
- Test case 1 - Drop-in change with `jammy`. No `GRUBCFG_PATH`. I was able to ssh into `tink@192.168.56.43`.
- Test case 2 - Drop-in change with `noble`. No `GRUBCFG_PATH`. I was NOT able to ssh into `tink@192.168.56.43`. Expected to fail as `noble` uses a `/boot` partition.
- Test case 3 - Drop-in change with `noble`. The value for `GRUBCFG_PATH` was set to `grub/grub.cfg`. The value …
> Allow custom path for grub.cfg
